name: Release
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1.21.1
        with:
          cache: true
          run-install: |
            - args: ['--frozen-lockfile']

      - name: Check
        run: vp run lint

      - name: Test
        run: vp run test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ./test-results.xml

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()

      - name: Build
        run: vp run build

      - name: Setup git user
        run: |
          git config user.name "${{ vars.GIT_USER }}"
          git config user.email "${{ vars.GIT_EMAIL }}"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: vp exec nx release -y
